exports.AUTHENTICATED = "AUTHENTICATED";

exports.MESSAGE = "MESSAGE";
exports.CLEAR_MESSAGE = "CLEAR_MESSAGE";

exports.LOADING_START = "LOADING_START";
exports.LOADING_END = "LOADING_END";

exports.CLEAR_PATH = "CLEAR_PATH";
exports.SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

exports.REGISTER_SUCCESS = "REGISTER_SUCCESS";

exports.GET_FIXED_VALUES = "GET_FIXED_VALUES";

exports.GET_SINGLE_BOOK = "GET_SINGLE_BOOK";

exports.GET_TEACHERS = "GET_TEACHERS";

exports.GET_SINGLE_TEACHER = "GET_SINGLE_TEACHER";

exports.GET_STUDENTS = "GET_STUDENTS";

exports.GET_SINGLE_STUDENT = "GET_SINGLE_STUDENT";

exports.GET_ADMINS = "GET_ADMINS";
exports.GET_SINGLE_ADMIN = "GET_SINGLE_ADMIN";
